#execution_env=local
execution_env=remote


appURL1=https://demowebshop.tricentis.com/
appURL2=https://tutorialsninja.com/demo/
email=rahulkakde9907@gmail.com
#password=test@123
password=test@123
searchProductName=iphone 